# Generated by Django 4.0.5 on 2022-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timelapse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelapseimage',
            name='imageName',
        ),
        migrations.AddField(
            model_name='timelapseimage',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='timelapseimage',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='timelapseimage',
            name='image',
            field=models.ImageField(upload_to='Timelapse/Images'),
        ),
    ]
